title: Demo Site
description: "Look at this beutiful demo"
theme: minima
baseurl: ""             # Leave empty; overridden by CLI --baseurl
url: ""                 # Leave empty for GitHub Pages

# Needed for relative assets
markdown: kramdown
permalink: pretty