name: Build and Deploy Jekyll Multi-Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build all Jekyll sites
        run: |
          mkdir -p _site

          # Build sub-sites
          for dir in $(find . -maxdepth 1 -type d ! -name '.' ! -name '_site' ! -name '.github' ! -name 'root-site'); do
            if [ -f "$dir/_config.yml" ]; then
              baseurl="/${dir#./}"
              echo "Building Jekyll site in $dir with baseurl=$baseurl"
              cd "$dir"
              bundle config set --local path 'vendor/bundle'
              bundle install --jobs 4 --retry 3
              bundle exec jekyll build -d "../_site/${dir#./}" --baseurl "$baseurl"
              cd ..
            fi
          done

          # Build root landing site
          cd root-site
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build -d "../_site"
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
