name: Build and Deploy Jekyll Multi-Site

on:
  push:
    branches:
      - main  # your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # match your local version

      # 3. Install Bundler & global gems
      - name: Install Jekyll & Bundler
        run: |
          gem install bundler jekyll webrick

      # 4. Build all Jekyll sites dynamically
      - name: Build all Jekyll sites
        run: |
          mkdir -p _site
          for dir in $(find . -maxdepth 1 -type d ! -name '.' ! -name '_site' ! -name '.github'); do
            if [ -f "$dir/_config.yml" ]; then
              baseurl="/${dir#./}"
              echo "Building Jekyll site in $dir with baseurl=$baseurl"

              if [ -f "$dir/Gemfile" ]; then
                (cd "$dir" && bundle install --path vendor/bundle && bundle exec jekyll build -d "../_site/${dir#./}" --baseurl "$baseurl")
              else
                (cd "$dir" && jekyll build -d "../_site/${dir#./}" --baseurl "$baseurl")
              fi
            fi
          done

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
          # force orphan branch for first deployment
          force_orphan: true
