name: Build and Deploy Jekyll Multi-Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build all Jekyll sites
        run: |
          mkdir -p _site
          for dir in $(find . -maxdepth 1 -type d ! -name '.' ! -name '_site' ! -name '.github'); do
            if [ -f "$dir/_config.yml" ]; then
              baseurl="/${dir#./}"
              echo "Building Jekyll site in $dir with baseurl=$baseurl"

              if [ -f "$dir/Gemfile" ]; then
                cd "$dir"
                bundle install --path vendor/bundle
                bundle exec jekyll build -d "../_site/${dir#./}" --baseurl "$baseurl"
                cd ..
              else
                cd "$dir"
                gem install jekyll webrick minima
                jekyll build -d "../_site/${dir#./}" --baseurl "$baseurl"
                cd ..
              fi
            fi
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
